name: pokemon_app
description: Simple pokemon search app
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: 3.3.7

dependencies: 
  app_theme:
    path: packages/app_theme
  bloc: ^8.1.0  
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_localizations:
    sdk: flutter
  get_it: ^7.2.0
  injectable: ^1.5.4
  intl: ^0.17.0
  persistent_storage:
    path: packages/storage/persistent_storage
  pokemon_api:
    path: packages/pokemon/pokemon_api
  shared_preferences: ^2.0.15
  storage:
    path: packages/storage/storage_interface
  

dev_dependencies:
  bloc_test: ^9.1.0
  build_runner: 
  flutter_test:
    sdk: flutter
  injectable_generator: 
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0

flutter:
  uses-material-design: true
  generate: true
